#########################################
# Sukka's Ruleset - Local DNS Mapping (Aladding)
# Last Updated: 2025-09-04T12:39:00.688Z
# Size: 49
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all rules are included in non_ip/domestic.conf already.
#########################################
DOMAIN-SUFFIX,redbookai.xyz
DOMAIN-SUFFIX,digital-nvme.com
DOMAIN-SUFFIX,yunsmartdns.com
################## EOF ##################
